# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Mathlogic/Project/cpu/cpu.srcs/sources_1/ip/Iimem/Iimem.xci
# IP: The module: 'Iimem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mathlogic/Project/cpu/cpu.srcs/sources_1/ip/Iimem/Iimem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Iimem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Mathlogic/Project/cpu/cpu.srcs/sources_1/ip/Iimem/Iimem.xci
# IP: The module: 'Iimem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mathlogic/Project/cpu/cpu.srcs/sources_1/ip/Iimem/Iimem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Iimem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
