######################################################################
#
# File name : sccomp_dataflow_compile.do
# Created on: Mon May 06 20:58:34 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Mathlogic\\modelsim\\win32pe\\vlib work
D:\\Mathlogic\\modelsim\\win32pe\\vlib msim

D:\\Mathlogic\\modelsim\\win32pe\\vlib msim/xil_defaultlib
D:\\Mathlogic\\modelsim\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

D:\\Mathlogic\\modelsim\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
D:\\Mathlogic\\modelsim\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

D:\\Mathlogic\\modelsim\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../cpu.srcs/sources_1/new/PC.v" \
"../../../cpu.srcs/sources_1/new/npc.v" \
"../../../cpu.srcs/sources_1/new/MUX6.v" \
"../../../cpu.srcs/sources_1/new/MUX4.v" \
"../../../cpu.srcs/sources_1/new/MUX3.v" \
"../../../cpu.srcs/sources_1/new/MUX2.v" \
"../../../cpu.srcs/sources_1/new/MUX1.v" \
"../../../cpu.srcs/sources_1/new/instr_decoder.v" \
"../../../cpu.srcs/sources_1/new/II.v" \
"../../../cpu.srcs/sources_1/new/control.v" \
"../../../cpu.srcs/sources_1/new/alu.v" \
"../../../cpu.srcs/sources_1/new/ADD.v" \
"../../../cpu.srcs/sources_1/new/RegFile.v" \

D:\\Mathlogic\\modelsim\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../cpu.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\Mathlogic\\modelsim\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../cpu.srcs/sources_1/ip/imem/sim/imem.v" \
"../../../cpu.srcs/sources_1/new/DMEM.v" \
"../../../cpu.srcs/sources_1/new/cpu.v" \
"../../../cpu.srcs/sources_1/new/sccomp_dataflow.v" \

# compile glbl module
D:\\Mathlogic\\modelsim\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

