# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/MathLogic/modelsim/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Mathlogic/Project/cpu/cpu.cache/wt [current_project]
set_property parent.project_path D:/Mathlogic/Project/cpu/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/Mathlogic/Project/cpu/test2019_for_cpu31.coe
add_files -quiet d:/Mathlogic/Project/cpu/cpu.srcs/sources_1/ip/Iimem/Iimem.dcp
set_property used_in_implementation false [get_files d:/Mathlogic/Project/cpu/cpu.srcs/sources_1/ip/Iimem/Iimem.dcp]
read_verilog -library xil_defaultlib {
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/PC.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/npc.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/MUX6.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/MUX4.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/MUX3.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/MUX2.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/MUX1.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/instr_decoder.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/II.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/control.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/alu.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/ADD.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/RegFile.v
  D:/Mathlogic/Project/CPU31_postsimulation/CPU31_postsimulation.sim/seg7x16.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/Divider.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/DMEM.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/cpu.v
  D:/Mathlogic/Project/cpu/cpu.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Mathlogic/Project/CPU31_postsimulation/CPU31_postsimulation.sim/icf.xdc
set_property used_in_implementation false [get_files D:/Mathlogic/Project/CPU31_postsimulation/CPU31_postsimulation.sim/icf.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
